spring.application.name=covered
server.port=${PORT:8080}


# The clock resets on every improvement, so this is basically saying "if there hasn't been an
# improvement in less than 200ms, terminate.
timefold.solver.termination.unimproved-spent-limit=200ms

# Absolute time ceiling regardless of progress
timefold.solver.termination.spent-limit=5s


spring.jpa.hibernate.ddl-auto=update


management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
